### ISSUE TITLE
image for background of landing

### ISSUE THREAD

**Issue by christopherjohnson1** [christopherjohnson1/personal-bio-site#8]
## User Story
When that page loads, you should see a high quality interesting landscape photo.

## AC
WHEN the page loads you see a high quality photo
AND it should take up the entire viewport
AND the image stays in place when scrolling
AND the content below scrolls up

## Dev Notes
- create a folder `images` that holds the images that are used on page in the personal-bio-site directory
- use the following CSS to style and link the background image to landing page
 ``` css
{
   background-image: url('https://via.placeholder.com/3000x2000');
   position: fixed;
   display: table;
   top: 0;
   left: 0;
   width: 100%;
   height: 100%;
   background-size: cover;
   background-position: center center;
   transform: translateZ(0);
   -webkit-transform: translateZ(0);
   will-change: transform;
}
```
